/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport } from './routes/0i9876r7s7ygs89grt7r9s8rbg9rdb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesPrintingServicesRouteImport } from './routes/services_.printing-services'
import { Route as ServicesFabricationInstallationRouteImport } from './routes/services_.fabrication-installation'
import { Route as ServicesEventManagementRouteImport } from './routes/services_.event-management'
import { Route as ServicesCreativeDevelopmentRouteImport } from './routes/services_.creative-development'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesPrintingRouteImport } from './routes/services.printing'
import { Route as ServicesOutdoorAdvertisingRouteImport } from './routes/services.outdoor-advertising'
import { Route as ServicesInstallationRouteImport } from './routes/services.installation'
import { Route as ServicesFabricationRouteImport } from './routes/services.fabrication'
import { Route as ServicesEventsRouteImport } from './routes/services.events'
import { Route as ServicesCreativeDesignRouteImport } from './routes/services.creative-design'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute =
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport.update({
    id: '/0i9876r7s7ygs89grt7r9s8rbg9rdb',
    path: '/0i9876r7s7ygs89grt7r9s8rbg9rdb',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrintingServicesRoute =
  ServicesPrintingServicesRouteImport.update({
    id: '/services_/printing-services',
    path: '/services/printing-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFabricationInstallationRoute =
  ServicesFabricationInstallationRouteImport.update({
    id: '/services_/fabrication-installation',
    path: '/services/fabrication-installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEventManagementRoute = ServicesEventManagementRouteImport.update({
  id: '/services_/event-management',
  path: '/services/event-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreativeDevelopmentRoute =
  ServicesCreativeDevelopmentRouteImport.update({
    id: '/services_/creative-development',
    path: '/services/creative-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/services/website-development',
    path: '/services/website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPrintingRoute = ServicesPrintingRouteImport.update({
  id: '/services/printing',
  path: '/services/printing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOutdoorAdvertisingRoute =
  ServicesOutdoorAdvertisingRouteImport.update({
    id: '/services/outdoor-advertising',
    path: '/services/outdoor-advertising',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstallationRoute = ServicesInstallationRouteImport.update({
  id: '/services/installation',
  path: '/services/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFabricationRoute = ServicesFabricationRouteImport.update({
  id: '/services/fabrication',
  path: '/services/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEventsRoute = ServicesEventsRouteImport.update({
  id: '/services/events',
  path: '/services/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreativeDesignRoute = ServicesCreativeDesignRouteImport.update({
  id: '/services/creative-design',
  path: '/services/creative-design',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRoute
  '/process': typeof ProcessRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/creative-development': typeof ServicesCreativeDevelopmentRoute
  '/services/event-management': typeof ServicesEventManagementRoute
  '/services/fabrication-installation': typeof ServicesFabricationInstallationRoute
  '/services/printing-services': typeof ServicesPrintingServicesRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRoute
  '/process': typeof ProcessRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/creative-development': typeof ServicesCreativeDevelopmentRoute
  '/services/event-management': typeof ServicesEventManagementRoute
  '/services/fabrication-installation': typeof ServicesFabricationInstallationRoute
  '/services/printing-services': typeof ServicesPrintingServicesRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRoute
  '/process': typeof ProcessRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services_/creative-development': typeof ServicesCreativeDevelopmentRoute
  '/services_/event-management': typeof ServicesEventManagementRoute
  '/services_/fabrication-installation': typeof ServicesFabricationInstallationRoute
  '/services_/printing-services': typeof ServicesPrintingServicesRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
    | '/services/website-development'
    | '/services/creative-development'
    | '/services/event-management'
    | '/services/fabrication-installation'
    | '/services/printing-services'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
    | '/services/website-development'
    | '/services/creative-development'
    | '/services/event-management'
    | '/services/fabrication-installation'
    | '/services/printing-services'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/studio'
    | '/work'
    | '/blog_/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
    | '/services/website-development'
    | '/services_/creative-development'
    | '/services_/event-management'
    | '/services_/fabrication-installation'
    | '/services_/printing-services'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute: typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  BlogRoute: typeof BlogRoute
  ProcessRoute: typeof ProcessRoute
  StudioRoute: typeof StudioRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesCreativeDesignRoute: typeof ServicesCreativeDesignRoute
  ServicesEventsRoute: typeof ServicesEventsRoute
  ServicesFabricationRoute: typeof ServicesFabricationRoute
  ServicesInstallationRoute: typeof ServicesInstallationRoute
  ServicesOutdoorAdvertisingRoute: typeof ServicesOutdoorAdvertisingRoute
  ServicesPrintingRoute: typeof ServicesPrintingRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesCreativeDevelopmentRoute: typeof ServicesCreativeDevelopmentRoute
  ServicesEventManagementRoute: typeof ServicesEventManagementRoute
  ServicesFabricationInstallationRoute: typeof ServicesFabricationInstallationRoute
  ServicesPrintingServicesRoute: typeof ServicesPrintingServicesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/0i9876r7s7ygs89grt7r9s8rbg9rdb': {
      id: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      path: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      fullPath: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      preLoaderRoute: typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/printing-services': {
      id: '/services_/printing-services'
      path: '/services/printing-services'
      fullPath: '/services/printing-services'
      preLoaderRoute: typeof ServicesPrintingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/fabrication-installation': {
      id: '/services_/fabrication-installation'
      path: '/services/fabrication-installation'
      fullPath: '/services/fabrication-installation'
      preLoaderRoute: typeof ServicesFabricationInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/event-management': {
      id: '/services_/event-management'
      path: '/services/event-management'
      fullPath: '/services/event-management'
      preLoaderRoute: typeof ServicesEventManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/creative-development': {
      id: '/services_/creative-development'
      path: '/services/creative-development'
      fullPath: '/services/creative-development'
      preLoaderRoute: typeof ServicesCreativeDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/services/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/printing': {
      id: '/services/printing'
      path: '/services/printing'
      fullPath: '/services/printing'
      preLoaderRoute: typeof ServicesPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/outdoor-advertising': {
      id: '/services/outdoor-advertising'
      path: '/services/outdoor-advertising'
      fullPath: '/services/outdoor-advertising'
      preLoaderRoute: typeof ServicesOutdoorAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/installation': {
      id: '/services/installation'
      path: '/services/installation'
      fullPath: '/services/installation'
      preLoaderRoute: typeof ServicesInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/fabrication': {
      id: '/services/fabrication'
      path: '/services/fabrication'
      fullPath: '/services/fabrication'
      preLoaderRoute: typeof ServicesFabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/events': {
      id: '/services/events'
      path: '/services/events'
      fullPath: '/services/events'
      preLoaderRoute: typeof ServicesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creative-design': {
      id: '/services/creative-design'
      path: '/services/creative-design'
      fullPath: '/services/creative-design'
      preLoaderRoute: typeof ServicesCreativeDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute: R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute,
  BlogRoute: BlogRoute,
  ProcessRoute: ProcessRoute,
  StudioRoute: StudioRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesCreativeDesignRoute: ServicesCreativeDesignRoute,
  ServicesEventsRoute: ServicesEventsRoute,
  ServicesFabricationRoute: ServicesFabricationRoute,
  ServicesInstallationRoute: ServicesInstallationRoute,
  ServicesOutdoorAdvertisingRoute: ServicesOutdoorAdvertisingRoute,
  ServicesPrintingRoute: ServicesPrintingRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesCreativeDevelopmentRoute: ServicesCreativeDevelopmentRoute,
  ServicesEventManagementRoute: ServicesEventManagementRoute,
  ServicesFabricationInstallationRoute: ServicesFabricationInstallationRoute,
  ServicesPrintingServicesRoute: ServicesPrintingServicesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
