/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport } from './routes/0i9876r7s7ygs89grt7r9s8rbg9rdb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPrintingRouteImport } from './routes/services.printing'
import { Route as ServicesOutdoorAdvertisingRouteImport } from './routes/services.outdoor-advertising'
import { Route as ServicesInstallationRouteImport } from './routes/services.installation'
import { Route as ServicesFabricationRouteImport } from './routes/services.fabrication'
import { Route as ServicesEventsRouteImport } from './routes/services.events'
import { Route as ServicesCreativeDesignRouteImport } from './routes/services.creative-design'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute =
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport.update({
    id: '/0i9876r7s7ygs89grt7r9s8rbg9rdb',
    path: '/0i9876r7s7ygs89grt7r9s8rbg9rdb',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrintingRoute = ServicesPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOutdoorAdvertisingRoute =
  ServicesOutdoorAdvertisingRouteImport.update({
    id: '/outdoor-advertising',
    path: '/outdoor-advertising',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInstallationRoute = ServicesInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFabricationRoute = ServicesFabricationRouteImport.update({
  id: '/fabrication',
  path: '/fabrication',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEventsRoute = ServicesEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCreativeDesignRoute = ServicesCreativeDesignRouteImport.update({
  id: '/creative-design',
  path: '/creative-design',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/0i9876r7s7ygs89grt7r9s8rbg9rdb': typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  '/blog': typeof BlogRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRouteWithChildren
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/creative-design': typeof ServicesCreativeDesignRoute
  '/services/events': typeof ServicesEventsRoute
  '/services/fabrication': typeof ServicesFabricationRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/outdoor-advertising': typeof ServicesOutdoorAdvertisingRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/services'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/services'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
  id:
    | '__root__'
    | '/'
    | '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
    | '/blog'
    | '/process'
    | '/services'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/services/creative-design'
    | '/services/events'
    | '/services/fabrication'
    | '/services/installation'
    | '/services/outdoor-advertising'
    | '/services/printing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute: typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute
  BlogRoute: typeof BlogRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StudioRoute: typeof StudioRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/0i9876r7s7ygs89grt7r9s8rbg9rdb': {
      id: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      path: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      fullPath: '/0i9876r7s7ygs89grt7r9s8rbg9rdb'
      preLoaderRoute: typeof R0i9876r7s7ygs89grt7r9s8rbg9rdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/printing': {
      id: '/services/printing'
      path: '/printing'
      fullPath: '/services/printing'
      preLoaderRoute: typeof ServicesPrintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/outdoor-advertising': {
      id: '/services/outdoor-advertising'
      path: '/outdoor-advertising'
      fullPath: '/services/outdoor-advertising'
      preLoaderRoute: typeof ServicesOutdoorAdvertisingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/installation': {
      id: '/services/installation'
      path: '/installation'
      fullPath: '/services/installation'
      preLoaderRoute: typeof ServicesInstallationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fabrication': {
      id: '/services/fabrication'
      path: '/fabrication'
      fullPath: '/services/fabrication'
      preLoaderRoute: typeof ServicesFabricationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/events': {
      id: '/services/events'
      path: '/events'
      fullPath: '/services/events'
      preLoaderRoute: typeof ServicesEventsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/creative-design': {
      id: '/services/creative-design'
      path: '/creative-design'
      fullPath: '/services/creative-design'
      preLoaderRoute: typeof ServicesCreativeDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesCreativeDesignRoute: typeof ServicesCreativeDesignRoute
  ServicesEventsRoute: typeof ServicesEventsRoute
  ServicesFabricationRoute: typeof ServicesFabricationRoute
  ServicesInstallationRoute: typeof ServicesInstallationRoute
  ServicesOutdoorAdvertisingRoute: typeof ServicesOutdoorAdvertisingRoute
  ServicesPrintingRoute: typeof ServicesPrintingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCreativeDesignRoute: ServicesCreativeDesignRoute,
  ServicesEventsRoute: ServicesEventsRoute,
  ServicesFabricationRoute: ServicesFabricationRoute,
  ServicesInstallationRoute: ServicesInstallationRoute,
  ServicesOutdoorAdvertisingRoute: ServicesOutdoorAdvertisingRoute,
  ServicesPrintingRoute: ServicesPrintingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute: R0i9876r7s7ygs89grt7r9s8rbg9rdbRoute,
  BlogRoute: BlogRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StudioRoute: StudioRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
